--Lệnh xóa Database nếu đã tồn tại
DROP DATABASE IF EXISTS BANHANG_NHOM4;
--Lệnh tạo Database 
CREATE DATABASE BANHANG_NHOM4 
GO
USE BANHANG_NHOM4;
--Tạo bảng KHÁCH HÀNG
	CREATE TABLE KHACHHANG
	(
		MAKHACHHANG CHAR(10) PRIMARY KEY,
		TENCONGTY NVARCHAR(50),
		TENGIAODICH NVARCHAR(50) NOT NULL,
		DIACHI NVARCHAR(50) NOT NULL,
		EMAIL VARCHAR(50) UNIQUE,
		DIENTHOAI VARCHAR(11) UNIQUE,
		FAX VARCHAR(10) UNIQUE
	)
--Tạo bảng NHÂN VIÊN
	CREATE TABLE NHANVIEN 
	(
		MANHANVIEN CHAR(10) PRIMARY KEY,
		HO NVARCHAR(10) NOT NULL,
		TEN NVARCHAR(10) NOT NULL,
		NGAYSINH DATE NOT NULL,
		NGAYLAMVIEC DATE NOT NULL,
		DIACHI NVARCHAR(50) NOT NULL,
		DIENTHOAI VARCHAR(10) UNIQUE,
		LUONGCOBAN DECIMAL(10,5) NOT NULL,
		PHUCAP DECIMAL(10,5)
	)
--Tạo bảng ĐƠN ĐẶT HÀNG
	CREATE TABLE DONDATHANG 
	(
		SOHOADON CHAR(10) PRIMARY KEY,
		MAKHACHHANG CHAR(10),
		MANHANVIEN CHAR(10),
		NGAYDATHANG DATE NOT NULL,
		NGAYGIAOHANG DATE ,
		NGAYCHUYENHANG DATE,
		NOIGIAOHANG NVARCHAR(50) NOT NULL
			FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
				ON DELETE CASCADE
				ON UPDATE CASCADE
	)
--Tạo bảng NHÀ CUNG CẤP
	CREATE TABLE NHACUNGCAP
	(
		MACONGTY CHAR(10) PRIMARY KEY,
		TENCONGTY NVARCHAR(50) NOT NULL,
		TENGIAODICH NVARCHAR(50) NOT NULL,
		DIACHI NVARCHAR(80),
		DIENTHOAI VARCHAR(11) UNIQUE,
		FAX VARCHAR(10) UNIQUE,
		EMAIL VARCHAR(50) UNIQUE
	)
--Tạo bảng LOẠI HÀNG
	CREATE TABLE LOAIHANG 
	(
		MALOAIHANG CHAR(10) PRIMARY KEY,
		TENLOAIHANG NVARCHAR(20)
	)
--Tạo Bảng MẶT HÀNG
	CREATE TABLE MATHANG 
	(
		MAHANG CHAR(10) PRIMARY KEY,
		TENHANG NVARCHAR(50) NOT NULL,
		MACONGTY CHAR(10),
		MALOAIHANG CHAR(10) ,
		SOLUONG FLOAT CHECK(SOLUONG >= 0),
		DONVITINH NVARCHAR(10) NOT NULL,
		GIAHANG MONEY CHECK(GIAHANG > 0),
			FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
				ON DELETE CASCADE
				ON UPDATE CASCADE
	)
--Tạo bảng CHI TIẾT ĐẶT HÀNG
	CREATE TABLE CHITIETDATHANG 
	(
		SOHOADON CHAR(10),
		MAHANG CHAR(10),
		GIABAN MONEY CHECK(GIABAN > 0),
		SOLUONG FLOAT CHECK(SOLUONG > 0),
		MUCGIAMGIA MONEY CHECK(MUCGIAMGIA >= 0),
			PRIMARY KEY (SOHOADON, MAHANG),
			FOREIGN KEY(SOHOADON) REFERENCES DONDATHANG(SOHOADON)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG)
				ON DELETE CASCADE
				ON UPDATE CASCADE
	)
--Ràng buộc Database
--Ràng buộc địa chỉ đa trị -> đơn trị
--Thêm bảng Quốc Gia
CREATE TABLE QUOCGIA
(
    MAQG char(10) PRIMARY KEY,
    TENQG nvarchar(100)
)
--Thêm bảng Thành Phố
CREATE TABLE THANHPHO
(
    MATP char(10) PRIMARY KEY,
    TENTP nvarchar(100),
    MAQG char(10),
    FOREIGN KEY (MAQG) REFERENCES QUOCGIA(MAQG)
        ON DELETE 
			CASCADE
        ON UPDATE 
			CASCADE
)
--Thêm bảng Quận Huyện
CREATE TABLE QUANHUYEN
(
    MAQH char(10) PRIMARY KEY,
    TENQH nvarchar(100),
    MATP char(10),
    FOREIGN KEY (MATP) REFERENCES THANHPHO(MATP)
        ON DELETE 
			CASCADE
        ON UPDATE 
			CASCADE
)
--Thêm bảng Phường Xã
CREATE TABLE PHUONGXA
(
    MAPX char(10) PRIMARY KEY,
    TENPX nvarchar(100),
    MAQH char(10),
    FOREIGN KEY (MAQH) REFERENCES QUANHUYEN(MAQH)
        ON DELETE 
			CASCADE
        ON UPDATE 
			CASCADE
)
--Tách cột địa chỉ bảng KHACHHANG thành 2 cột
ALTER TABLE KHACHHANG
DROP COLUMN DIACHI
ALTER TABLE KHACHHANG
ADD MAPX char(10),
    SONHATENDUONG nvarchar(100)
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_MAPX 
		FOREIGN KEY (MAPX) REFERENCES PHUONGXA(MAPX)
			ON DELETE 
				CASCADE
			ON UPDATE 
				CASCADE;
--Tách cột địa chỉ bảng NHACUNGCAP thành 2 cột
ALTER TABLE NHACUNGCAP
DROP COLUMN DIACHI
ALTER TABLE NHACUNGCAP
ADD MAPX char(10),
    SONHATENDUONG nvarchar(100)
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT FK_NHACUNGCAP_MAPX 
		FOREIGN KEY (MAPX) REFERENCES PHUONGXA(MAPX)
			ON DELETE 
				NO ACTION
			ON UPDATE 
				NO ACTION;
--Tách cột địa chỉ bảng DONDATHANG thành 2 cột
ALTER TABLE DONDATHANG
DROP COLUMN NOIGIAOHANG
ALTER TABLE DONDATHANG
ADD MAPX char(10),
    DIACHICUTHE nvarchar(100)
ALTER TABLE DONDATHANG
ADD CONSTRAINT FK_DONDATHANG_MAPX 
		FOREIGN KEY (MAPX) REFERENCES PHUONGXA(MAPX)
			ON DELETE 
				NO ACTION
			ON UPDATE 
				NO ACTION;
--Ràng buộc các giá trị thứ tự về ngày
ALTER TABLE DONDATHANG
ADD CONSTRAINT DF_DONDATHANG_NGAYDATHANG 
		DEFAULT GETDATE() FOR NGAYDATHANG,
    CONSTRAINT CK_DONDATHANG_NGAYCHUYENHANG 
		CHECK(NGAYCHUYENHANG >= NGAYDATHANG),
    CONSTRAINT CK_DONDATHANG_NGAYGIAOHANG 
		CHECK(NGAYGIAOHANG >= NGAYCHUYENHANG);
--Ràng buộc về giá trị mặc định của số lượng và mức giảm giá
ALTER TABLE CHITIETDATHANG
ADD CONSTRAINT DF_CHITIETDATHANG_SOLUONG 
		DEFAULT 1 FOR SOLUONG,
    CONSTRAINT DF_CHITIETDATHANG_MUCGIAMGIA 
		DEFAULT 0 FOR MUCGIAMGIA;
--Ràng buộc về số điện thoại 10 or 11 số cho bảng Khách Hàng
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KHACHHANG_DIENTHOAI 
		CHECK(DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
		   OR DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]');
--Ràng buộc về số điện thoại 10 or 11 số cho bảng Nhân Viên
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NHANVIEN_DIENTHOAI 
		CHECK(DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
		   OR DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]');
--Ràng buộc về số điện thoại 10 or 11 số cho bảng Nhà Cung Cấp
ALTER TABLE NHACUNGCAP
	ADD CONSTRAINT CK_NHACUNGCAP_DIENTHOAI 
		CHECK(DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
		   OR DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]');
--Ràng buộc về email bắt đầu bằng chữ cái + phải có @
ALTER TABLE KHACHHANG
    ADD CONSTRAINT CK_KHACHHANG_EMAIL
		CHECK (Email LIKE '[a-zA-Z]%@%_');
ALTER TABLE NHACUNGCAP
    ADD CONSTRAINT CK_NHACUNGCAP_EMAIL
		CHECK (Email LIKE '[a-zA-Z]%@%_');
--Ràng buộc ngày sinh của nhân viên phải đủ 18 tuổi và không quá 60 tuổi
ALTER TABLE NHANVIEN
	ADD CONSTRAINT CK_NHANVIEN_NGAYSINH
		CHECK (DATEDIFF(DAY, Ngaysinh, GETDATE()) /360 >= 18 
		   And DATEDIFF(DAY, Ngaysinh, GETDATE()) /360 <=60  );
--Ràng buộc TENCONGTY trong bảng KHACHHANG
ALTER TABLE KHACHHANG
ADD CONSTRAINT DF_KHACHHANG_TENCONGTY
	DEFAULT N'Khách hàng cá nhân' FOR TENCONGTY;
