CREATE DATABASE BANHANG ;
GO
 
	USE BANHANG;
	GO
	CREATE TABLE KHACHHANG
	(
		MAKHACHHANG VARCHAR(10) PRIMARY KEY,
		TENCONGTY NVARCHAR(50) NOT NULL,
		TENGIAODICH NVARCHAR(50) NOT NULL,
		DIACHI NVARCHAR(50) NOT NULL,
		EMAIL VARCHAR(20),
		DIENTHOAI CHAR(10),
		FAX NVARCHAR(10)
	)

	CREATE TABLE NHANVIEN 
	(
		MANHANVIEN VARCHAR(10) PRIMARY KEY,
		HO VARCHAR(10) NOT NULL,
		TEN NVARCHAR(10) NOT NULL,
		NGAYSINH DATE NOT NULL,
		NGAYLAMVIEC DATE NOT NULL,
		DIACHI NVARCHAR(50) NOT NULL,
		DIENTHOAI CHAR(10),
		LUONGCOBAN INT NOT NULL,
		PHUCAP INT
	)

	CREATE TABLE DONDATHANG 
	(
		SOHOADON VARCHAR(10) PRIMARY KEY,
		MAKHACHHANG VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKHACHHANG),
		MANHANVIEN VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
		NGAYDATHANG DATE NOT NULL,
		NGAYGIAOHANG DATE ,
		NGAYCHUYENHANG DATE,
		NOIGIAOHANG NVARCHAR(50) NOT NULL

	)

	CREATE TABLE NHACUNGCAP
	(
		MACONGTY VARCHAR(10) PRIMARY KEY,
		TENCONGTY VARCHAR(50) NOT NULL,
		TENGIAODICH VARCHAR(50) NOT NULL,
		DIACHI NVARCHAR(80),
		DIENTHOAI VARCHAR(12),
		FAX NVARCHAR(10),
		EMAIL VARCHAR(20) NOT NULL
	)

	CREATE TABLE LOAIHANG 
	(
		MALOAIHANG VARCHAR(10) PRIMARY KEY,
		TENLOAIHANG VARCHAR(20)
	)
	
	CREATE TABLE MATHANG 
	(
		MAHANG VARCHAR(10) PRIMARY KEY,
		TENHANG NVARCHAR(20) NOT NULL,
		MACONGTY VARCHAR(10) FOREIGN KEY REFERENCES NHACUNGCAP(MACONGTY),
		MALOAIHANG VARCHAR(10) FOREIGN KEY REFERENCES LOAIHANG(MALOAIHANG),
		SOLUONG INT CHECK(SOLUONG >= 0),
		DONVITINH VARCHAR(10) NOT NULL,
		GIAHANG MONEY CHECK(GIAHANG > 0)
	)

	CREATE TABLE CHITIETDATHANG 
	(
		SOHOADON VARCHAR(10),
		MAHANG VARCHAR(10),
		GIABAN FLOAT CHECK(GIABAN > 0),
		SOLUONG INT CHECK(SOLUONG > 0),
		MUCGIAMGIA FLOAT CHECK(MUCGIAMGIA >= 0),

		FOREIGN KEY(SOHOADON) REFERENCES DONDATHANG(SOHOADON),
		FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG),
		PRIMARY KEY (SOHOADON, MAHANG)
	)


	

